[buildPlans.levska-mono]
family = "Levska Mono"
spacing = "normal"
serifs = "sans"

[buildPlans.levska-mono.variants.design]
turn-v = "curly"
capital-b = "more-asymmetric"
capital-d = "standard"
capital-g = "toothless-corner"
capital-j = "serifed-both-sides"
capital-k = "curly"
capital-r = "curly"
capital-y = "curly"
a = "doublestorey"
b = "toothless-corner"
d = "toothless-corner"
f = "serifed"
g = "opendoublestorey"
h = "tailed"
i = "serifed-flat-tailed"
j = "serifed"
k = "curly"
l = "serifed-flat-tailed"
m = "earless-corner-double-arch-shortleg"
n = "motion-serifed-straight"
p = "eared"
q = "earless-rounded"
r = "earless-rounded-serifed"
t = "flat-hook-short-neck"
u = "toothless-corner"
v = "curly"
w = "straight"
x = "curly"
y = "straight-turn"
z = "curly"
eszet = "sulzbacher"
lambda = "straight"
zero = "reverse-slashed"
one = "nobase"
three = "flattop"
four = "open"
six = "straight-bar"
seven = "crossbar"
asterisk = "hexlow"
underscore = "high"
caret = "high"
ampersand = "upper-open"
at = "threefold"
dollar = "open"
percent = "rings-connected"
bar = "force-upright"
lig-ltgteq = "slanted"
ascii-single-quote = "raised-comma"

	[buildPlans.levska-mono.ligations]
	inherits = "php"
